# Generated by Django 2.1.15 on 2020-09-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linux_ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('linux_name', models.CharField(max_length=32)),
                ('linux_cpu', models.IntegerField(default=10)),
                ('linux_notes', models.CharField(max_length=258)),
            ],
            options={
                'db_table': 'Linux',
            },
        ),
    ]
